### ISSUE TITLE
following readme instructions gives a DB error

### ISSUE THREAD

**Issue by ashleygwilliams** [mozilla/login.webmaker.org#354]
following a `$ npm install`

```
Ashleys-MacBook-Pro:login.webmaker.org ag_dubs$ node app.js
db/index.js: DB setup error
 undefined Cannot read property 'database' of undefined
/Users/ag_dubs/Projects/login.webmaker.org/app/db/models/index.js:18
  var user = sequelize.import(__dirname + "/user.js");
                      ^
TypeError: Cannot read property 'import' of undefined
    at module.exports (/Users/ag_dubs/Projects/login.webmaker.org/app/db/models/index.js:18:23)
    at module.exports (/Users/ag_dubs/Projects/login.webmaker.org/app/db/index.js:21:45)
    at module.exports (/Users/ag_dubs/Projects/login.webmaker.org/app/http/server.js:28:30)
    at Object.<anonymous> (/Users/ag_dubs/Projects/login.webmaker.org/app.js:7:32)
```

**Comment by ashleygwilliams** [comment]
nevermind. figured this out.
